---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: docker-cleanup-default
    box: generic/ubuntu2204
provisioner:
  name: ansible
  playbooks:
    create: create.yml
    converge: converge.yml
    destroy: destroy.yml
verifier:
  name: ansible
